name: Telegram Bot Issue
description: Auto-created by Telegram bot
title: "[Telegram]: "
labels: ["telegram", "auto-triage"]
body:
  - type: textarea
    id: message
    attributes:
      label: User Message
      description: Original message from Telegram
    validations:
      required: true
  - type: input
    id: chat-id
    attributes:
      label: Telegram Chat ID
    validations:
      required: true
  - type: dropdown
    id: type
    attributes:
      label: Issue Type
      options:
        - bug
        - feature
        - question
    validations:
      required: true
